### ISSUE TITLE
!!! Exception during processing!!! 'str' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by Diamond-Shark-art** [tritant/ComfyUI_CreaPrompt#7]
Hi, i came across CreaPrompt because of this: https://civitai.com/models/621380/flux1-multi-random-prompts-ultimate-sd-upscale?modelVersionId=694657

When i run it in ComfyUI i get this error message:

!!! Exception during processing!!! 'str' object cannot be interpreted as an integer
Traceback (most recent call last):
  File "C:\Users\Gebruiker\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 152, in recursive_execute
    output_data, output_ui = get_output_data(obj, input_data_all)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 82, in get_output_data
    return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\execution.py", line 75, in map_node_over_list
    results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Gebruiker\Downloads\ComfyUI_windows_portable_nvidia\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_CreaPrompt\creaprompt.py", line 102, in create_prompt
    for c in range(prompts_count):
             ^^^^^^^^^^^^^^^^^^^^
TypeError: 'str' object cannot be interpreted as an integer

![Scherm­afbeelding 2024-08-09 om 18 48 52](https://github.com/user-attachments/assets/c666a2cd-8e56-4197-b500-3771e2c354d4)

Is it anything i did wrong? I have everything updated.

**Comment by tritant** [comment]
Enter the correct values ​​in the last 4 fields and save the WF with the new values or remove and replace CreaPrompt complete node and save the WF


![image](https://github.com/user-attachments/assets/4146f55b-c0a3-45f6-abe9-83e7a4ecf74b)

**Comment by Diamond-Shark-art** [comment]
That fixed it, thanks for the quick help and reply!
